import Head from "next/head";
import styles from './Layout.module.scss'
import Headerbar from "./header/Headerbar";

export default function Layout({ children, title = "HP by Nextjs" }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="img/main1.jpg" /> */}
      </Head>

    <Headerbar />

      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
        <p className={styles.footer_copy}>&copy;2022 ShunD Tech. All rights reserved </p>
      </footer>
    </>
  );
}